version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: seashell_user
      POSTGRES_PASSWORD: seashell_pass
      POSTGRES_DB: seashell_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seashell_user"]
      interval: 10s
      retries: 5